import type {
  AgentProfile,
  BootstrapData,
  TaskDetail,
  TaskSummary,
} from "./model.js";

const ago = (minutes: number): string => new Date(Date.now() - minutes * 60_000).toISOString();

export const demoAgents: AgentProfile[] = [
  {
    id: "agent-mira",
    name: "Mira",
    initials: "MI",
    role: "Lead investigator",
    owner: "Clock",
    driver: "Claude Code",
    status: "working",
    capabilities: ["stream", "follow-up", "resume", "cancel"],
    currentTaskId: "task-auth",
    color: "#9d8cff",
  },
  {
    id: "agent-patch",
    name: "Patch",
    initials: "PA",
    role: "Implementation specialist",
    owner: "Platform",
    driver: "Codex",
    status: "available",
    capabilities: ["JSONL", "continuation", "cancel"],
    currentTaskId: null,
    color: "#5bb8ff",
  },
  {
    id: "agent-finch",
    name: "Finch",
    initials: "FI",
    role: "Test & review",
    owner: "Clock",
    driver: "Pi",
    status: "reviewing",
    capabilities: ["stream", "steer", "follow-up", "resume", "cancel"],
    currentTaskId: "task-webhook",
    color: "#45d8a4",
  },
  {
    id: "agent-orbit",
    name: "Orbit",
    initials: "OR",
    role: "Parallel scout",
    owner: "Shared crew",
    driver: "Oh My Pi",
    status: "available",
    capabilities: ["stream", "steer", "subagents", "resume", "cancel"],
    currentTaskId: null,
    color: "#ffaf5e",
  },
];

export const demoTasks: TaskSummary[] = [
  {
    id: "task-webhook",
    title: "Fix flaky webhook retry spec",
    repository: "cdotlock/mob-agent-crew",
    branch: "main",
    status: "review_ready",
    resolution: "unreviewed",
    updatedAt: ago(4),
    unread: 3,
    participantIds: ["agent-mira", "agent-patch", "agent-finch"],
    summary: "A bounded retry fix is ready with fresh test evidence.",
  },
  {
    id: "task-auth",
    title: "Review credential handoff boundary",
    repository: "cdotlock/mob-agent-crew",
    branch: "main",
    status: "running",
    resolution: "unreviewed",
    updatedAt: ago(11),
    unread: 1,
    participantIds: ["agent-mira", "agent-orbit"],
    summary: "Two agents are tracing token ownership and publication gates.",
  },
  {
    id: "task-serializer",
    title: "Harden event serializer",
    repository: "lunaverse/agent-gateway",
    branch: "release/1.8",
    status: "failed",
    resolution: "unreviewed",
    updatedAt: ago(58),
    unread: 0,
    participantIds: ["agent-patch"],
    summary: "The implementation run exited before publishing its patch.",
  },
  {
    id: "task-readme",
    title: "Clarify one-shot driver behavior",
    repository: "cdotlock/mob-agent-crew",
    branch: "main",
    status: "completed",
    resolution: "accepted",
    updatedAt: ago(190),
    unread: 0,
    participantIds: ["agent-finch"],
    summary: "Documentation update accepted after one review pass.",
  },
];

const webhookTask: TaskDetail = {
  ...demoTasks[0]!,
  description:
    "The retry suite fails intermittently when two delivery attempts share the same timestamp. Find the race, keep the public API stable, and return a reviewable patch with fresh tests.",
  baseRef: "main@7c9d2a1",
  maxDelegationDepth: 3,
  delegationDepth: 2,
  budgetUsed: 4.82,
  budgetLimit: 8,
  messages: [
    {
      id: "msg-1",
      actorId: "user-clock",
      actorName: "Clock",
      actorKind: "human",
      actorInitials: "CL",
      content:
        "@Mira reproduce the flaky webhook retry spec. Keep the public API stable and delegate implementation once you have a narrow cause.",
      createdAt: ago(43),
      runId: null,
      artifactIds: [],
      delivery: "sent",
    },
    {
      id: "msg-2",
      actorId: "agent-mira",
      actorName: "Mira",
      actorKind: "agent",
      actorInitials: "MI",
      content:
        "I reproduced the failure 7/50 times. The attempt key is derived from a millisecond timestamp, so simultaneous retries overwrite the in-memory entry before persistence. I’m handing the smallest safe change to @Patch.",
      createdAt: ago(31),
      runId: "run-scout",
      artifactIds: ["artifact-diagnosis"],
      delivery: "sent",
    },
    {
      id: "msg-3",
      actorId: "system",
      actorName: "Crew control",
      actorKind: "system",
      actorInitials: "CC",
      content:
        "Mira delegated implementation to Patch. Patch received the task thread, revision main@7c9d2a1, and diagnosis.md — not Mira’s writable workspace.",
      createdAt: ago(29),
      runId: "run-fix",
      artifactIds: [],
      delivery: "sent",
    },
    {
      id: "msg-4",
      actorId: "agent-patch",
      actorName: "Patch",
      actorKind: "agent",
      actorInitials: "PA",
      content:
        "Implemented a monotonic attempt suffix behind the existing key helper and added a concurrent retry case. The controller published the patch from my isolated run and released its write lease.",
      createdAt: ago(16),
      runId: "run-fix",
      artifactIds: ["artifact-patch"],
      delivery: "sent",
    },
    {
      id: "msg-5",
      actorId: "agent-finch",
      actorName: "Finch",
      actorKind: "agent",
      actorInitials: "FI",
      content:
        "Applied the patch to a clean snapshot. The focused retry suite passed 100/100 and the full test run is green. I found no public contract change; this is ready for human review.",
      createdAt: ago(5),
      runId: "run-verify",
      artifactIds: ["artifact-tests"],
      delivery: "sent",
    },
  ],
  runs: [
    {
      id: "run-scout",
      agentId: "agent-mira",
      role: "Investigate",
      status: "succeeded",
      attempt: 1,
      startedAt: ago(42),
      finishedAt: ago(30),
      summary: "Reproduced the race and published a bounded diagnosis.",
      parentRunId: null,
    },
    {
      id: "run-fix",
      agentId: "agent-patch",
      role: "Implement",
      status: "succeeded",
      attempt: 1,
      startedAt: ago(28),
      finishedAt: ago(15),
      summary: "Published patch r1 from an isolated writer lease.",
      parentRunId: "run-scout",
    },
    {
      id: "run-verify",
      agentId: "agent-finch",
      role: "Verify",
      status: "succeeded",
      attempt: 1,
      startedAt: ago(14),
      finishedAt: ago(4),
      summary: "Fresh checkout passed focused and full tests.",
      parentRunId: "run-fix",
    },
  ],
  artifacts: [
    {
      id: "artifact-diagnosis",
      name: "diagnosis.md",
      kind: "report",
      summary: "Race isolated to a timestamp-derived attempt key.",
      producerAgentId: "agent-mira",
      createdAt: ago(30),
      revision: "main@7c9d2a1",
      content:
        "Concurrent retries can receive the same attempt key within one millisecond. Preserve the public helper, add an internal monotonic suffix, and cover simultaneous delivery attempts.",
      language: "markdown",
    },
    {
      id: "artifact-patch",
      name: "webhook-retry.patch",
      kind: "patch",
      summary: "+24 −5 across two files",
      producerAgentId: "agent-patch",
      createdAt: ago(15),
      revision: "r1 · 89f42b7",
      content: [
        "diff --git a/src/webhooks/retry-key.ts b/src/webhooks/retry-key.ts",
        "index f314a88..5fd4411 100644",
        "--- a/src/webhooks/retry-key.ts",
        "+++ b/src/webhooks/retry-key.ts",
        "@@ -8,7 +8,12 @@ export function retryKey(deliveryId: string, now = Date.now()) {",
        "-  return `${deliveryId}:${now}`;",
        "+  const sequence = nextAttemptSequence(deliveryId, now);",
        "+  return `${deliveryId}:${now}:${sequence}`;",
        " }",
        "+",
        "+function nextAttemptSequence(deliveryId: string, now: number) {",
        "+  return attemptSequences.increment(`${deliveryId}:${now}`);",
        "+}",
      ].join("\n"),
      language: "diff",
    },
    {
      id: "artifact-tests",
      name: "test-report.json",
      kind: "report",
      summary: "148 passed · 0 failed · 31.4s",
      producerAgentId: "agent-finch",
      createdAt: ago(4),
      revision: "r1 · 89f42b7",
      content:
        '{\n  "focused": { "runs": 100, "passed": 100 },\n  "full": { "passed": 148, "failed": 0 },\n  "durationSeconds": 31.4\n}',
      language: "json",
    },
  ],
};

const authTask: TaskDetail = {
  ...demoTasks[1]!,
  description:
    "Trace credential ownership from agent run to human-approved publication. Flag any path that lets a runtime approve its own SCM write.",
  baseRef: "main@7c9d2a1",
  maxDelegationDepth: 2,
  delegationDepth: 1,
  budgetUsed: 2.16,
  budgetLimit: 6,
  messages: [
    {
      id: "auth-msg-1",
      actorId: "user-clock",
      actorName: "Clock",
      actorKind: "human",
      actorInitials: "CL",
      content: "@Mira audit the credential handoff. Ask @Orbit for an independent threat pass.",
      createdAt: ago(23),
      runId: null,
      artifactIds: [],
      delivery: "sent",
    },
    {
      id: "auth-msg-2",
      actorId: "agent-orbit",
      actorName: "Orbit",
      actorKind: "agent",
      actorInitials: "OR",
      content:
        "Independent pass started from an immutable revision. I’m checking approval identity and whether run tokens can reach the publisher.",
      createdAt: ago(10),
      runId: "run-orbit",
      artifactIds: [],
      delivery: "sent",
    },
  ],
  runs: [
    {
      id: "run-mira-auth",
      agentId: "agent-mira",
      role: "Primary audit",
      status: "running",
      attempt: 1,
      startedAt: ago(22),
      finishedAt: null,
      summary: "Tracing run-token scope through the publication request.",
      parentRunId: null,
    },
    {
      id: "run-orbit",
      agentId: "agent-orbit",
      role: "Threat review",
      status: "running",
      attempt: 1,
      startedAt: ago(9),
      finishedAt: null,
      summary: "Reviewing approval actor boundaries.",
      parentRunId: "run-mira-auth",
    },
  ],
  artifacts: [],
};

const serializerTask: TaskDetail = {
  ...demoTasks[2]!,
  description: "Make event serialization reject unknown actor kinds without breaking stored events.",
  baseRef: "release/1.8@a18be21",
  maxDelegationDepth: 2,
  delegationDepth: 0,
  budgetUsed: 0.71,
  budgetLimit: 4,
  messages: [
    {
      id: "serializer-msg-1",
      actorId: "agent-patch",
      actorName: "Patch",
      actorKind: "agent",
      actorInitials: "PA",
      content:
        "The driver exited before emitting a terminal event. No patch was published; logs remain attached for a clean retry.",
      createdAt: ago(58),
      runId: "run-serializer",
      artifactIds: ["artifact-error-log"],
      delivery: "sent",
    },
  ],
  runs: [
    {
      id: "run-serializer",
      agentId: "agent-patch",
      role: "Implement",
      status: "failed",
      attempt: 1,
      startedAt: ago(67),
      finishedAt: ago(58),
      summary: "Driver process exited with code 1 before artifact publication.",
      parentRunId: null,
    },
  ],
  artifacts: [
    {
      id: "artifact-error-log",
      name: "driver-stderr.log",
      kind: "log",
      summary: "Process exited with code 1",
      producerAgentId: "agent-patch",
      createdAt: ago(58),
      revision: "release/1.8@a18be21",
      content: "Error: credential home is not initialized for profile agent-patch\nexit code: 1",
      language: "text",
    },
  ],
};

const readmeTask: TaskDetail = {
  ...demoTasks[3]!,
  description: "Explain continuation semantics for one-shot drivers.",
  baseRef: "main@3a9d1b2",
  maxDelegationDepth: 2,
  delegationDepth: 0,
  budgetUsed: 0.48,
  budgetLimit: 3,
  messages: [],
  runs: [],
  artifacts: [],
};

const demoDetails = new Map<string, TaskDetail>([
  [webhookTask.id, webhookTask],
  [authTask.id, authTask],
  [serializerTask.id, serializerTask],
  [readmeTask.id, readmeTask],
]);

export const demoBootstrap: BootstrapData = {
  workspace: {
    id: "workspace-demo",
    name: "Lunaverse engineering",
    environment: "Railway · demo fallback",
  },
  currentUser: {
    id: "user-clock",
    name: "Clock",
    initials: "CL",
  },
  tasks: demoTasks,
  agents: demoAgents,
};

export function getDemoTask(taskId: string): TaskDetail | null {
  const task = demoDetails.get(taskId);
  return task ? structuredClone(task) : null;
}

export function createDemoDetail(task: TaskSummary, initialMessage: string): TaskDetail {
  return {
    ...task,
    description: initialMessage,
    baseRef: `${task.branch}@HEAD`,
    maxDelegationDepth: 2,
    delegationDepth: 0,
    budgetUsed: 0,
    budgetLimit: 5,
    messages: [
      {
        id: `message-${crypto.randomUUID()}`,
        actorId: "user-clock",
        actorName: "Clock",
        actorKind: "human",
        actorInitials: "CL",
        content: initialMessage,
        createdAt: new Date().toISOString(),
        runId: null,
        artifactIds: [],
        delivery: "sent",
      },
    ],
    runs: [],
    artifacts: [],
  };
}
